### ISSUE TITLE
Tabs icon-on-top theme variant doesn't apply to child Tab components

### ISSUE THREAD

**Issue by rolandoisidoro** [vaadin/vaadin-tabs#164]
### Description
Variant `theme="icon-on-top"` doesn't work when set once in the parent `vaadin-tabs` element as `theme="small"` variant does. 

### Expected outcome
All `vaadin-tab` child components should inherit the variant styles from the host.

### Actual outcome
Every `vaadin-tab` child components doesn't get affected by the host variant.

### Steps to reproduce
1. Put a `vaadin-tabs` element in the page;
2. Add a `theme="icon-on-top"` attribut to the `vaadin-tabs` element;
2. Add some `vaadin-tab` children without a theme attribute.

### Browsers Affected
All browsers.

**Comment by web-padawan** [comment]
Thanks for the issue. This is not currently supported because of the fact that `vaadin-tab` components are not in the shadow DOM. We only propagate `theme` to the components that are placed inside Shadow DOM.

This is also valid for the following components:

- `vaadin-accordion` and `vaadin-accordion-panel`
- `vaadin-list-box` and `vaadin-item`
- `vaadin-radio-group` and `vaadin-radio-button`
- `vaadin-checkbox-group` and `vaadin-checkbox`

I don't think we want to change this for all of the components in this list.

**Comment by rolandoisidoro** [comment]
@web-padawan , thanks for the prompt reply. So how does `theme="small"` work?

**Comment by web-padawan** [comment]
The themes like `small` and `minimal` apply to the slotted tabs as you can see here:
https://github.com/vaadin/vaadin-tabs/blob/87d98e1d4cfd3f5a4dc28666b8ae650443219298/theme/lumo/vaadin-tabs-styles.html#L136-L143

Closing as won't fix.
