### ISSUE TITLE
Vertical scrollbar is hidden in Safari

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-tabs#37]
The vertical scrollbar should be always shown because it's necessary to indicate to a user that there's more item and the element is scrollable.

**Comment by jouni** [comment]
Vertical scrollbars should follow the platform default, and the default for macOS/Safari is the overlay style.

We should not fix all usability issues in the default theme. Users of this element should take care that in their app the tabs are usable.

If they restrict the height of the element so that it becomes scrollable, they should either use a different theme (Valo and Material will provide extra visual cues about overflow) or add custom CSS on top of the default theme.

**Comment by limonte** [comment]
Makes sense.

**Comment by jouni** [comment]
Still, a good observation from the tests, which I was more or less expecting!

I was initially going to implement the visual hint about the overflow in the default theme already, but then I thought it adds too much complexity to it and makes customization harder on top of it.

So, instead, we will do the more complex styles in the proper themes.
